## [특강] Numpy, Pandas, Matplotlib

### 2. Pandas 기본 구조: Series와 DataFrame

#### 2.1 Series와 DataFrame
Series

In [1]:
import pandas as pd  #pd 판다스의 별칭

In [3]:
scores = pd.Series([90,85,88])
scores, type(scores) # 출력 왼쪽은 열

(0    90
 1    85
 2    88
 dtype: int64,
 pandas.Series)

Pandas 구조

DataFrame
= 여러 개의 Series가 모인 2차원 표

        A열         B열         C열
     ┌────────┐  ┌────────┐  ┌────────┐
0    │   A0   │  │   B0   │  │   C0   │
1    │   A1   │  │   B1   │  │   C1   │
2    │   A2   │  │   B2   │  │   C2   │
3    │   A3   │  │   B3   │  │   C3   │
     └────────┘  └────────┘  └────────┘
       Series      Series      Series

각 열 하나 = Series
여러 Series가 모이면 = DataFrame

Series
= 1차원
= 열 하나

DataFrame
= 2차원
= 여러 열이 모인 표

컬럼
= 열

DataFrame
- 2차원(행,열) 구조체,

In [8]:
data = {
    "이름":['김철수','이영희','박민수'],
    "부서":['개발','기획','개발'],
    "급여":[4500,5200,4800]
}

df = pd.DataFrame(data)
df

    이름  부서    급여
0  김철수  개발  4500
1  이영희  기획  5200
2  박민수  개발  4800

#### 2.2 데이터 탐색 속성(shape, dtypes)과 진단(info, describe)

- 탐색적 데이터 분석(EDA)
- df.info() : 누락치 확인 (Non-Null Count) → 데이터의 구조 확인 → 컬럼명, 자료형, 결측치 여부

- dtype: 통계가 가능한 자료형인지 체크, 잘못된 데이터가 있는지의 여부를 확인하고 -> 치환 -> 자료형 변환
    - github에서도 status를 항상 먼저 확인하는 거랑 같음
- df.describe() : DataFrame 안의 숫자 데이터들을 한 번에 요약해서 통계값을 보여주는 함수 → 숫자 데이터의 통계 확인 → 평균, 최소, 최대, 중앙값 등 / 튀는 값이 있는지 확인하기 위해(섞여있는 데이터 중에 튀는 값들을 보기 위해)

In [9]:
print("df.info()")
df.info()   # 연산이 가능한 형태인지, 데이터 정보를 확인합니다.

df.info()
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      3 non-null      str
 1   부서      3 non-null      str
 2   급여      3 non-null      int64
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [10]:
df.describe()

                급여
count     3.000000
mean   4833.333333
std     351.188458
min    4500.000000
25%    4650.000000
50%    4800.000000
75%    5000.000000
max    5200.000000

#### 2.3 데이터 변경 및 인덱스 제어(set_index, reset_index)

In [13]:
df['급여'], type(df['급여'])
df['보너스'] = df['급여'] * 0.1

df

    이름  부서    급여    보너스
0  김철수  개발  4500  450.0
1  이영희  기획  5200  520.0
2  박민수  개발  4800  480.0

In [ ]:
# 인덱스를 변경 : 행이 보통 인덱스 형태인데 인덱스를 특정 내용으로 변경도 할 수 있어요~ : set_index()
df_indexed = df.set_index('이름')
df_indexed

     부서    급여    보너스
이름
김철수  개발  4500  450.0
이영희  기획  5200  520.0
박민수  개발  4800  480.0

In [ ]:
# 인덱스를 다시 숫자형 인덱스로 변경하는 경우 : reset_index()
df_restored = df_indexed.reset_index()
df_restored

    이름  부서    급여    보너스
0  김철수  개발  4500  450.0
1  이영희  기획  5200  520.0
2  박민수  개발  4800  480.0

#### 2.4 Pandas Series & DataFrame 브로드캐스팅 연산

- axis:0 > 행의 인덱스 기준
- axis:1 > 컬럼(열) 기준

In [16]:
df = pd.DataFrame({
    '중간고사':[80,95,70],
    '기말고사':[85,90,75],
})

df

   중간고사  기말고사
0    80    85
1    95    90
2    70    75

In [ ]:
# 숫자가 아닌, 인덱스 명명을 하고 싶을 때, 
df = pd.DataFrame({
    '중간고사':[80,95,70],
    '기말고사':[85,90,75],
}, index=['김철수','이영희','박민수'])

df

     중간고사  기말고사
김철수    80    85
이영희    95    90
박민수    70    75

In [19]:
score_means = df.mean(axis=0) # 인덱스 기준
score_means

중간고사    81.666667
기말고사    83.333333
dtype: float64

In [21]:
score_means = df.mean(axis=1) # 인덱스 기준
score_means

김철수    82.5
이영희    92.5
박민수    72.5
dtype: float64

In [ ]:
score_gap = df.sub(score_means,axis=1) #컬럼 기준/ 한번에 연산 / 브로드캐스팅
score_gap

          중간고사      기말고사
김철수  -1.666667  1.666667
이영희  13.333333  6.666667
박민수 -11.666667 -8.333333

### 3. Pandas 정밀 조회 및 결측치 제어

#### 3.1  loc와 iloc를 활용한 행·열 선택
- loc(location)랑 iloc(index location)는 둘 다 Pandas에서 원하는 행/열을 골라내는 조회 방법
- "큰 데이터 중, 데이터 전처리 때 일부 데이터들을 추출해서 가공하기 전 많이 사용하는 기능입니다."
- loc  → 행/열의 이름(label) 기준으로 선택 / 이름으로 찾기
    - df.loc[행 라벨(이름)]
    - df.loc[행 라벨(이름), 컬럼(열)라벨(이름)]
    - (슬라이싱도 가능!) df.loc[시작행:종료행,[컬럼1,컬럼2]] # 특정 범위의 행과 열을 선택도 가능합니다.
    - df.loc[...,시작컬럼:종료컬럼]
- iloc → 행/열의 위치 번호(integer position) 기준으로 선택 / 몇 번째 위치인지 번호로 찾기
    - loc와 사용방법이 동일하지만, 인덱스 번호
    - 범위를 설정할 경우 종료번호는 포함x (인덱스 규칙 동일하게 적용)
        - (e.g) iloc[0:2,0:2] -> 행/열 모두 2는 포함x

In [ ]:
# loc 예시
import pandas as pd

df = pd.DataFrame({
    '나이':[25,30,35,40],
    '점수':[80,95,70,85],
    '등급':['B','A','C','B']
},index=['user1','user2','user3','user4'])

df

       나이  점수 등급
user1  25  80  B
user2  30  95  A
user3  35  70  C
user4  40  85  B

In [ ]:
df.loc['user1']  # 행 이름 선택
type(df.loc['user1']) #타입이 나와요~

pandas.Series

In [ ]:
df.loc['user1','점수'] # 열 이름 선택

np.int64(80)

In [ ]:
df.loc['user1':'user3',['나이','등급']] # 행 슬라이싱과 열 추출

       나이 등급
user1  25  B
user2  30  A
user3  35  C

In [ ]:
df.loc['user1':'user2','점수':'등급'] # 행/열 슬라이싱 추출

       점수 등급
user1  80  B
user2  95  A

In [13]:
# iloc 예시
df.iloc[0:1,0:3]

       나이  점수 등급
user1  25  80  B

#### 3.2 불리언 인덱싱과 query() 조건 검색

1. 불리언 인덱싱
- 조건식을 만들고,컬럼별 값의 결과가 True인 행만 가져오는 방법 "데이터 전처리 할 때, 아주 많이 씁니다~"
- 조건이 여러개 있는 경우, 
    - & : and 연산자 / 조건 모두가 "참"일 때
    - | : or 연산자 / 조건 중 하나라도 "참"일 때

In [14]:
df['나이'] >= 30

user1    False
user2     True
user3     True
user4     True
Name: 나이, dtype: bool

In [ ]:
df[df['나이'] >= 30]  # 참인 조건들만 추출

       나이  점수 등급
user2  30  95  A
user3  35  70  C
user4  40  85  B

In [ ]:
(df['나이'] >= 30) & (df['점수'] >= 80) # 논리 연산자 사용시, 앞뒤 데이터 조건식은 ()소괄호 필수!!!!

user1    False
user2     True
user3    False
user4     True
dtype: bool

In [ ]:
df[(df['나이'] >= 30) & (df['점수'] >= 80)] # 논리 연산자 사용해서 데이터 추출하기!

       나이  점수 등급
user2  30  95  A
user4  40  85  B

2. query() 메서드 필터링
- 조건식을 문자열처럼 써서 행을 필터링하는 메서드

In [ ]:
df.query('나이 >= 30 and 점수 >= 80') # 조건식 전체를 문자열로 넘기기 때문에 조건 전체에 따옴표가 필수!!!!!

       나이  점수 등급
user2  30  95  A
user4  40  85  B

#### 3.3 결측치(Missing Data) 7대 처리 기법
3.3.1 결측치 탐지 및 현황 요약 (Detection)
- 결측치 = 값이 비어 있거나 누락된 데이터의 위치를 찾는 것

- 데이터프레임의 결측치는 가장 먼저 info() 에서 확인합니다.
- 결측치인지 확인하는 메서드 : isna(),isnull()
    - 결측치다  → True / 결측치 아니다 → False
- [중요!!] True = 1로 인식! / False = 0으로 인식!
    (e.g) True + True = 2 / False + 1 = 1

- 결측값 표현
    - np.nan → NumPy의 결측값
    - pd.NA  → Pandas의 결측값
    - None   → Python의 값 없음

In [20]:
import numpy as np

# 결측치 : np.nan, pd.NA , NONE
raw_df = pd.DataFrame({'A': [1, np.nan, 3], 'B': [pd.NA, 5, 6], 'C': [7, 8, 9]})

raw_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       2 non-null      float64
 1   B       2 non-null      object
 2   C       3 non-null      int64
dtypes: float64(1), int64(1), object(1)
memory usage: 204.0+ bytes

In [ ]:
raw_df.isna() # → 비어 있으면 True!!!!

       A      B      C
0  False   True  False
1   True  False  False
2  False  False  False

In [ ]:
raw_df.isna().sum() # 비어있는 곳에 브로드캐스팅!!!!

A    1
B    1
C    0
dtype: int64

3.3.2 결측치 삭제 (Drop)
- dropna() 메서드 사용하며, 행/열 모두 제거 가능
- axis=0 → 특정 행에 결측치가 있다면 삭제 (이게 기본!!!)
- axis=1 → 특정 열에 결측치가 있다면 삭제

In [22]:
raw_df

     A     B  C
0  1.0  <NA>  7
1  NaN     5  8
2  3.0     6  9

In [21]:
# 행 기준에서 결측치 삭제 예시

raw_df.dropna() # 기본이라서 axis=0 입력 안해도 되여~

     A  B  C
2  3.0  6  9

In [23]:
# 열 기준에서 결측치 삭제 예시

raw_df.dropna(axis=1)

   C
0  7
1  8
2  9

3.3.3 통계적 대푯값 대치 (Imputation)
- 결측치를 그냥 지우지 않고, 그 컬럼을 대표할 만한 값으로 채우는 것
- 통계적 대푯값 3가지
    - 평균 mean()
    - 중앙값 median() 
        - 튀는 값들의 영향을 덜 받으므로 중앙값을 대치하기도 합니다. 평균값을 넣으면 데이터가 희석될 가능성이 크므로~
        - 중앙값은 양끝값보다 가운데 위치를 보는 값
    - 최빈값 mode

- 대표 메서드 
    - fillna() → 결측치를 채운다
    - mean() → 평균값을 구한다

In [30]:
# 예시

df_age = pd.DataFrame({'나이': [20, 25, None, 30, 95]})

median_val = df_age['나이'].median()
print("중앙값:",median_val)

df_age['나이'] = df_age['나이'].fillna(median_val)

df_age

중앙값: 27.5

     나이
0  20.0
1  25.0
2  27.5
3  30.0
4  95.0

3.3.4 시계열 직전/직후 값 대치 (Forward / Backward Fill)
- 결측치를 앞이나 뒤에 있는 값으로 채우는 방법으로, 특히 날짜·시간 순서가 있는 데이터에서 많이 쓴다.
- 반대로 Backward Fill(후방 채우기)은 바로 다음 값을 끌어와서 결측치를 채웁니다.
- 대표 메서드
    - ffill() : 앞쪽에 있는 값으로 대체
    - bfill() : 뒷쪽에 있는 값으로 대체

In [31]:
ts_df = pd.DataFrame({'온도': [18.2, None, None, 21.0]})

ts_df.ffill()

     온도
0  18.2
1  18.2
2  18.2
3  21.0

In [32]:
ts_df.bfill()

     온도
0  18.2
1  21.0
2  21.0
3  21.0

3.3.5 선형 보간법 (Linear Interpolation)
- 앞값과 뒷값 사이를 직선처럼 이어서, 중간의 결측값을 추정해서 채우는 방법
- 앞뒤의 실제 값을 이용해서 그 사이 변화가 일정하다고 가정하고 결측값을 계산하는 방법
- 시간 순서가 있고 값이 비교적 연속적으로 변하는 온도, 센서 측정값 같은 데이터 처리에 사용
- 대표 메서드
    - interpolate()

- method='linear'는 “어떤 방식으로 보간할지 지정하는 옵션”
    - linear는 앞뒤 값을 직선처럼 이어서 가운데를 계산한다. 
    - [중요!!!] : interpolate()의 기본값이 원래 linear

In [34]:
speed_df = pd.DataFrame({'속도': [10.0, None, None, 40.0]})


speed_df['속도'] = speed_df['속도'].interpolate(method='linear')
speed_df

     속도
0  10.0
1  20.0
2  30.0
3  40.0

In [35]:
speed_df.interpolate()

     속도
0  10.0
1  20.0
2  30.0
3  40.0

3.3.6 이상 기호 치환 및 수치형 변환 (Replace & Type Casting)
- 이상한 데이터를 교체 / 이상한 값을 정리하고 → 계산 가능한 타입으로 바꾸는 과정
- 지저분한 문자열 데이터를 정리한 뒤, 계산 가능한 숫자 데이터로 바꾸는 전처리 과정
- 대표 메서드
    - replace() : 결측치로 대체됨 / 이상 기호 정리
    - pandas.to_numeric() : 숫자 자료형으로 변환
    - errors='coerce'는 숫자로 바꿀 수 없는 값이 있으면 에러를 내지 말고 NaN으로 바꿔라는 뜻

# 처리과정 
---
원본 데이터
'60', '70', '-', '90'

↓ replace()

'60', '70', <NA>, '90'

↓ pd.to_numeric()

60.0, 70.0, NaN, 90.0
---

In [36]:
survey_df = pd.DataFrame({'점수': [85, -999, '?', 95]})

survey_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   점수      4 non-null      object
dtypes: object(1)
memory usage: 164.0+ bytes

In [ ]:
survey_df.describe()  # object 문자열이 있기 때문에,

        점수
count    4
unique   4
top     85
freq     1

In [ ]:
survey_df['점수'] = survey_df['점수'].replace([-999,'?'], pd.NA)

survey_df

     점수
0    85
1  <NA>
2  <NA>
3    95

In [ ]:
survey_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   점수      2 non-null      object
dtypes: object(1)
memory usage: 164.0+ bytes

In [42]:
survey_df['점수'] = pd.to_numeric(survey_df['점수'], errors='coerce')

survey_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   점수      2 non-null      float64
dtypes: float64(1)
memory usage: 164.0 bytes

In [ ]:
survey_df.describe()

              점수
count   2.000000
mean   90.000000
std     7.071068
min    85.000000
25%    87.500000
50%    90.000000
75%    92.500000
max    95.000000

3.3.7 결측 여부 지표 변수 생성 (Missing Indicator)
- “원래 그 값이 결측치였는지 아닌지”를 따로 표시하는 새 컬럼을 만드는 것
- 원래 결측치였던 행을 True/False 또는 1/0으로 표시하는 보조 변수 / 결측치를 가공해버리면 나중에 결측이었는지 아니였는지 추적이 불가능하므로!!!!
- 원래 값이 있었음 → False = 0
- 원래 값이 비어 있었음 → True = 1


- isna()로 결측 여부 확인 + 필요하면 astype(int)로 0/1 변환

In [44]:
user_df = pd.DataFrame({'소득': [300, None, 450, None]})

user_df['미응답여부'] =  user_df['소득'].isna()


user_df

      소득  미응답여부
0  300.0  False
1    NaN   True
2  450.0  False
3    NaN   True

#### 3.4 그룹화 집계(groupby)와 .to_numpy() 상호 변환
- Pandas에서 데이터를 요약한 뒤, 필요하면 NumPy 배열로 넘기는 흐름
- 왜 바꾸냐면, Pandas는 표 구조와 라벨을 다루기 편하고, NumPy는 수치 계산에 강하니까 필요에 따라 넘겨 쓰는 거야.

- groupby() :  같은 기준끼리 묶어서 집계 / 같은 범주끼리 묶어서 평균, 합계, 개수 같은 통계를 내는 기능
- .to_numpy() :  Pandas의 Series나 DataFrame을 NumPy 배열로 바꾸는 메서드

- numeric_only=True → 숫자형 컬럼만 평균 계산에 사용
    - .mean(numeric_only=True) : 문자열 컬럼은 제외하고 숫자 컬럼만 평균 내라 / 조건 명시!!!!!!!

##### 구조
---
Pandas로 원본 데이터 정리
↓
groupby()로 그룹별 요약
↓
필요하면 .to_numpy()
↓
NumPy 배열로 수치 계산
---

In [45]:
sales_df = pd.DataFrame({'지점': ['서울', '서울', '부산', '부산'], '매출': [100, 150, 80, 120]})

sales_df

   지점   매출
0  서울  100
1  서울  150
2  부산   80
3  부산  120

In [48]:
group_df = sales_df.groupby('지점').mean(numeric_only=True)
group_df

       매출
지점
부산  100.0
서울  125.0

In [49]:
sales_df['매출'].to_numpy(dtype=np.float64)

array([100., 150.,  80., 120.])

====

# 수업 내용
----
- 비트(bit) = 컴퓨터가 정보를 표현하는 가장 작은 단위
- 바이트(byte) = 비트 8개를 묶은 단위

# 데이터 분석 파이프라인

NumPy
↓
계산 가능한 숫자 구조 만들기

Pandas
↓
데이터에 의미를 붙이고 표로 관리하기

Pandas 조회/정제
↓
필요한 데이터만 골라서 깨끗하게 만들기

groupby
↓
데이터를 요약하기

Matplotlib
↓
결과를 눈으로 확인하기

# 머신러닝 흐름

원본 데이터

↓ Pandas

데이터 확인
결측치 처리
필요한 열 선택
조건 필터링

↓ NumPy

모델이 계산할 수 있는 숫자 배열

↓ Machine Learning Model

학습 / 예측

↓ Matplotlib

결과 시각화

# 전체 구조
- NumPy → Pandas → 데이터 정제/조회 → Matplotlib

숫자 데이터를 배열로 다룬다
    ↓
표 형태의 데이터로 다룬다
    ↓
필요한 행/열만 찾는다
    ↓
결측치나 이상한 값을 정리한다
    ↓
통계를 내거나 그룹별로 묶는다
    ↓
그래프로 시각화해서 패턴을 본다

1. NumPy — “숫자를 계산하기 좋은 구조로 만든다”

- NumPy는 숫자 계산용 배열을 다루는 도구
- 왜 굳이 NumPy를 쓰냐? 숫자가 엄청 많아졌을 때 빠르게 계산하기 좋기 때문
- “숫자들이 지금 어떤 모양으로 메모리에 들어 있고, 어느 방향으로 계산할 것인가?”
- bit, byte, int64가 왜 나오냐?
    - int64 → 정수 자료형 → 하나의 숫자를 64bit로 표현
    - NumPy는 대량의 숫자를 처리하니까 각 숫자를 메모리에 어떻게 저장할지도 중요해지는 것

In [ ]:
# 파이썬 구조
scores = [80, 90, 70]

# numpy 구조
import numpy as np
scores = np.array([80, 90, 70])

2. Pandas — “숫자 배열에 이름을 붙여서 표처럼 다룬다”
- 엑셀 같은 표를 Python으로 조작하는 도구
- Pandas의 핵심 자료구조 : 
    - Series    → 1차원
    - DataFrame → 2차원 표

In [ ]:
# Numpy 구조
[[100, 20],
 [200, 30],
 [150, 25]]

# Pandas 구조 : 행과 열에 의미를 붙여서 다룬다
상품    매출    판매량
A      100      20
B      200      30
C      150      25

3. loc / iloc / query — “내가 원하는 데이터만 골라낸다”
- loc → 이름으로 찾기
- iloc → 위치 번호로 찾기
- query → 조건으로 찾기

In [ ]:
# dataframe 구조
df.loc[]
df.iloc[]
df.query()

In [ ]:
# 파이썬 예시
if score >= 80:

# 판다스 예시
df[df["score"] >= 80]

4. 결측치 처리 — “더러운 데이터를 청소한다”
 - 값이 없을 때 이 데이터를 삭제할 건가? 다른 값으로 채울 건가? 추정할 건가?

5. groupby — “같은 종류끼리 묶어서 요약한다” "같은 종류끼리 묶어서 연산한다" / SQL에서도 나옴

6. Matplotlib — “숫자만 보지 말고 그림으로 확인한다”
- 데이터를 정리하고 계산했으면 마지막에는:“그래서 이 데이터에 어떤 패턴이 있는데?” 를 봐야 하잖아.그걸 그래프로 보여주는 게 Matplotlib이야.
Matplotlib의 목적은 예쁜 그래프 만들기가 아니야.핵심은 숫자로만 보면 잘 안 보이는 패턴을 눈으로 확인하는 것!!!!

- scatter → 두 변수의 관계

- bar → 항목별 크기 비교

- histogram → 데이터가 어디에 몰려 있는지

- boxplot → 분포와 이상치 확인