## [특강] Numpy, Pandas, Matplotlib

### 2. Pandas 기본 구조: Series와 DataFrame

#### 2.1 Series와 DataFrame
Series

In [1]:
import pandas as pd  #pd 판다스의 별칭

In [3]:
scores = pd.Series([90,85,88])
scores, type(scores) # 출력 왼쪽은 열

(0    90
 1    85
 2    88
 dtype: int64,
 pandas.Series)

Pandas 구조

DataFrame
= 여러 개의 Series가 모인 2차원 표

        A열         B열         C열
     ┌────────┐  ┌────────┐  ┌────────┐
0    │   A0   │  │   B0   │  │   C0   │
1    │   A1   │  │   B1   │  │   C1   │
2    │   A2   │  │   B2   │  │   C2   │
3    │   A3   │  │   B3   │  │   C3   │
     └────────┘  └────────┘  └────────┘
       Series      Series      Series

각 열 하나 = Series
여러 Series가 모이면 = DataFrame

Series
= 1차원
= 열 하나

DataFrame
= 2차원
= 여러 열이 모인 표

컬럼
= 열

DataFrame
- 2차원(행,열) 구조체,

In [8]:
data = {
    "이름":['김철수','이영희','박민수'],
    "부서":['개발','기획','개발'],
    "급여":[4500,5200,4800]
}

df = pd.DataFrame(data)
df

    이름  부서    급여
0  김철수  개발  4500
1  이영희  기획  5200
2  박민수  개발  4800

#### 2.2 데이터 탐색 속성(shape, dtypes)과 진단(info, describe)

- 탐색적 데이터 분석(EDA)
- df.info() : 누락치 확인 (Non-Null Count) → 데이터의 구조 확인 → 컬럼명, 자료형, 결측치 여부

- dtype: 통계가 가능한 자료형인지 체크, 잘못된 데이터가 있는지의 여부를 확인하고 -> 치환 -> 자료형 변환
    - github에서도 status를 항상 먼저 확인하는 거랑 같음
- df.describe() : DataFrame 안의 숫자 데이터들을 한 번에 요약해서 통계값을 보여주는 함수 → 숫자 데이터의 통계 확인 → 평균, 최소, 최대, 중앙값 등 / 튀는 값이 있는지 확인하기 위해(섞여있는 데이터 중에 튀는 값들을 보기 위해)

In [9]:
print("df.info()")
df.info()   # 연산이 가능한 형태인지, 데이터 정보를 확인합니다.

df.info()
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      3 non-null      str
 1   부서      3 non-null      str
 2   급여      3 non-null      int64
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [10]:
df.describe()

                급여
count     3.000000
mean   4833.333333
std     351.188458
min    4500.000000
25%    4650.000000
50%    4800.000000
75%    5000.000000
max    5200.000000

#### 2.3 데이터 변경 및 인덱스 제어(set_index, reset_index)

In [13]:
df['급여'], type(df['급여'])
df['보너스'] = df['급여'] * 0.1

df

    이름  부서    급여    보너스
0  김철수  개발  4500  450.0
1  이영희  기획  5200  520.0
2  박민수  개발  4800  480.0

In [ ]:
# 인덱스를 변경 : 행이 보통 인덱스 형태인데 인덱스를 특정 내용으로 변경도 할 수 있어요~ : set_index()
df_indexed = df.set_index('이름')
df_indexed

     부서    급여    보너스
이름
김철수  개발  4500  450.0
이영희  기획  5200  520.0
박민수  개발  4800  480.0

In [ ]:
# 인덱스를 다시 숫자형 인덱스로 변경하는 경우 : reset_index()
df_restored = df_indexed.reset_index()
df_restored

    이름  부서    급여    보너스
0  김철수  개발  4500  450.0
1  이영희  기획  5200  520.0
2  박민수  개발  4800  480.0

#### 2.4 Pandas Series & DataFrame 브로드캐스팅 연산

- axis:0 > 행의 인덱스 기준
- axis:1 > 컬럼(열) 기준

In [16]:
df = pd.DataFrame({
    '중간고사':[80,95,70],
    '기말고사':[85,90,75],
})

df

   중간고사  기말고사
0    80    85
1    95    90
2    70    75

In [ ]:
# 숫자가 아닌, 인덱스 명명을 하고 싶을 때, 
df = pd.DataFrame({
    '중간고사':[80,95,70],
    '기말고사':[85,90,75],
}, index=['김철수','이영희','박민수'])

df

     중간고사  기말고사
김철수    80    85
이영희    95    90
박민수    70    75

In [19]:
score_means = df.mean(axis=0) # 인덱스 기준
score_means

중간고사    81.666667
기말고사    83.333333
dtype: float64

In [ ]:
score_gap = df.sub(score_means,axis=1) #컬럼 기준/ 한번에 연산 / 브로드캐스팅
score_gap

          중간고사      기말고사
김철수  -1.666667  1.666667
이영희  13.333333  6.666667
박민수 -11.666667 -8.333333

### 3. Pandas 정밀 조회 및 결측치 제어

#### 3.1  loc와 iloc를 활용한 행·열 선택

#### 3.2 불리언 인덱싱과 query() 조건 검색

불리언 인덱싱

query() 필터링

#### 3.3 결측치(Missing Data) 7대 처리 기법
3.3.1 결측치 탐지 및 현황 요약 (Detection)

3.3.2 결측치 삭제 (Drop)

3.3.3 통계적 대푯값 대치 (Imputation)

3.3.4 시계열 직전/직후 값 대치 (Forward / Backward Fill)

3.3.5 선형 보간법 (Linear Interpolation)

3.3.6 이상 기호 치환 및 수치형 변환 (Replace & Type Casting)

3.3.7 결측 여부 지표 변수 생성 (Missing Indicator)

#### 3.4 그룹화 집계(groupby)와 .to_numpy() 상호 변환

# 수업 내용
----
- 비트(bit) = 컴퓨터가 정보를 표현하는 가장 작은 단위
- 바이트(byte) = 비트 8개를 묶은 단위

# 데이터 분석 파이프라인

NumPy
↓
계산 가능한 숫자 구조 만들기

Pandas
↓
데이터에 의미를 붙이고 표로 관리하기

Pandas 조회/정제
↓
필요한 데이터만 골라서 깨끗하게 만들기

groupby
↓
데이터를 요약하기

Matplotlib
↓
결과를 눈으로 확인하기

# 머신러닝 흐름

원본 데이터

↓ Pandas

데이터 확인
결측치 처리
필요한 열 선택
조건 필터링

↓ NumPy

모델이 계산할 수 있는 숫자 배열

↓ Machine Learning Model

학습 / 예측

↓ Matplotlib

결과 시각화

# 전체 구조
- NumPy → Pandas → 데이터 정제/조회 → Matplotlib

숫자 데이터를 배열로 다룬다
    ↓
표 형태의 데이터로 다룬다
    ↓
필요한 행/열만 찾는다
    ↓
결측치나 이상한 값을 정리한다
    ↓
통계를 내거나 그룹별로 묶는다
    ↓
그래프로 시각화해서 패턴을 본다

1. NumPy — “숫자를 계산하기 좋은 구조로 만든다”

- NumPy는 숫자 계산용 배열을 다루는 도구
- 왜 굳이 NumPy를 쓰냐? 숫자가 엄청 많아졌을 때 빠르게 계산하기 좋기 때문
- “숫자들이 지금 어떤 모양으로 메모리에 들어 있고, 어느 방향으로 계산할 것인가?”
- bit, byte, int64가 왜 나오냐?
    - int64 → 정수 자료형 → 하나의 숫자를 64bit로 표현
    - NumPy는 대량의 숫자를 처리하니까 각 숫자를 메모리에 어떻게 저장할지도 중요해지는 것

In [ ]:
# 파이썬 구조
scores = [80, 90, 70]

# numpy 구조
import numpy as np
scores = np.array([80, 90, 70])

2. Pandas — “숫자 배열에 이름을 붙여서 표처럼 다룬다”
- 엑셀 같은 표를 Python으로 조작하는 도구
- Pandas의 핵심 자료구조 : 
    - Series    → 1차원
    - DataFrame → 2차원 표

In [ ]:
# Numpy 구조
[[100, 20],
 [200, 30],
 [150, 25]]

# Pandas 구조 : 행과 열에 의미를 붙여서 다룬다
상품    매출    판매량
A      100      20
B      200      30
C      150      25

3. loc / iloc / query — “내가 원하는 데이터만 골라낸다”
- loc → 이름으로 찾기
- iloc → 위치 번호로 찾기
- query → 조건으로 찾기

In [ ]:
# dataframe 구조
df.loc[]
df.iloc[]
df.query()

In [ ]:
# 파이썬 예시
if score >= 80:

# 판다스 예시
df[df["score"] >= 80]

4. 결측치 처리 — “더러운 데이터를 청소한다”
 - 값이 없을 때 이 데이터를 삭제할 건가? 다른 값으로 채울 건가? 추정할 건가?

5. groupby — “같은 종류끼리 묶어서 요약한다” "같은 종류끼리 묶어서 연산한다" / SQL에서도 나옴

6. Matplotlib — “숫자만 보지 말고 그림으로 확인한다”
- 데이터를 정리하고 계산했으면 마지막에는:“그래서 이 데이터에 어떤 패턴이 있는데?” 를 봐야 하잖아.그걸 그래프로 보여주는 게 Matplotlib이야.
Matplotlib의 목적은 예쁜 그래프 만들기가 아니야.핵심은 숫자로만 보면 잘 안 보이는 패턴을 눈으로 확인하는 것!!!!

- scatter → 두 변수의 관계

- bar → 항목별 크기 비교

- histogram → 데이터가 어디에 몰려 있는지

- boxplot → 분포와 이상치 확인